version: "3.7"

services:

  bank_server:
    build: .
    restart: always
    container_name: server
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysql_db:3306/bank?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysql_db
    command: sh -c './wait-for mysql_db:3306 -- npm start'

  mysql_db:
    image: "mysql/mysql-server"
    restart: always
    networks:
      - springmysql-net
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bank
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin

networks:
  springmysql-net:
    driver: bridge